[package]
name = "prettyplease-bug"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
prettyplease = "0.1"
syn = { version = "1", features = ["full", "extra-traits"] }
quote = "1"